"""Learning domain ports (Protocols)."""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .entities import KnowledgeItem, ModelVersion


class KnowledgeBasePort(Protocol):
    async def save(self, item: KnowledgeItem) -> KnowledgeItem: ...
    async def get_all(self, knowledge_type: str | None = None) -> list[KnowledgeItem]: ...
    async def get_by_id(self, item_id: UUID) -> KnowledgeItem | None: ...


class ModelPort(Protocol):
    def save(self, version: ModelVersion) -> None: ...
    def load(self, version_id: UUID) -> object: ...
    def list_versions(self, model_type: str | None = None) -> list[ModelVersion]: ...
    def get_active(self, model_type: str) -> ModelVersion | None: ...
