"""ClaudeStrategy — wraps ClaudeAdapter into the new StrategyPort."""
from __future__ import annotations

import json
import logging

import anthropic
from tenacity import retry, stop_after_attempt, wait_exponential

from market.domain.entities import CandleSeries
from strategy.domain.entities import Direction, Signal, SignalSource

logger = logging.getLogger(__name__)

_MODEL = "claude-sonnet-4-6"

_SYSTEM_PROMPT = """You are a professional Forex trading analyst and risk manager.
Your role is to evaluate trading signals generated by technical analysis and machine learning models,
and provide a final trading recommendation with clear reasoning.

You must respond in valid JSON with exactly this structure:
{
  "direction": "BUY" | "SELL" | "HOLD",
  "confidence": <float 0.0-1.0>,
  "reasoning": "<concise explanation, max 200 words>"
}

Rules:
- Do NOT act as a price predictor. Evaluate the evidence provided.
- A HOLD is valid and encouraged when signals conflict or context is ambiguous.
- Confidence above 0.70 in the OPPOSITE direction to the TA+ML consensus will VETO their recommendation.
- Be conservative: capital preservation over profit chasing.
"""


def _build_prompt(candles: CandleSeries, ta_signal: Signal, ml_signal: Signal) -> str:
    last_candles_str = ""
    if candles.candles:
        recent = candles.candles[-5:]
        last_candles_str = "\n".join(
            f"  [{c.time.isoformat()}] O={c.open:.5f} H={c.high:.5f} "
            f"L={c.low:.5f} C={c.close:.5f} V={c.volume:.0f}"
            for c in recent
        )

    ta_ctx = json.dumps(ta_signal.context, indent=2)
    ml_ctx = json.dumps(ml_signal.context, indent=2)

    return f"""# Forex Trading Signal Evaluation

## Instrument: {candles.instrument_symbol} | Timeframe: {candles.timeframe.value}

## Recent Candles (last 5):
{last_candles_str}

## Technical Analysis Signal
Direction: {ta_signal.direction.value}
Confidence: {ta_signal.confidence:.2f}
Indicators:
{ta_ctx}

## Machine Learning Signal (XGBoost 3-class classifier)
Direction: {ml_signal.direction.value}
Confidence: {ml_signal.confidence:.2f}
Probabilities:
{ml_ctx}

## Your Task
Review the TA and ML signals above. Consider:
1. Do the signals agree or conflict?
2. Are the TA indicators consistent with the ML probabilities?
3. Is the current market context suitable for a trade?

Respond with your JSON assessment."""


class ClaudeStrategy:
    """Uses Claude as a reasoning/veto layer on top of TA and ML signals."""

    def __init__(self, api_key: str, model: str = _MODEL) -> None:
        self._client = anthropic.Anthropic(api_key=api_key)
        self._model = model

    async def generate(self, candles: CandleSeries, **kwargs) -> Signal:
        ta_signal: Signal | None = kwargs.get("ta_signal")
        ml_signal: Signal | None = kwargs.get("ml_signal")

        if ta_signal is None or ml_signal is None:
            return Signal(
                instrument_symbol=candles.instrument_symbol,
                timeframe=candles.timeframe,
                direction=Direction.HOLD,
                confidence=0.0,
                source=SignalSource.CLAUDE,
                reasoning="No TA/ML context provided",
            )

        prompt = _build_prompt(candles, ta_signal, ml_signal)

        try:
            result = await self._call_api(prompt)
        except Exception as exc:
            logger.error("Claude API failed: %s", exc)
            return Signal(
                instrument_symbol=candles.instrument_symbol,
                timeframe=candles.timeframe,
                direction=Direction.HOLD,
                confidence=0.0,
                source=SignalSource.CLAUDE,
                reasoning=f"API error: {exc}",
            )

        return Signal(
            instrument_symbol=candles.instrument_symbol,
            timeframe=candles.timeframe,
            direction=result["direction"],
            confidence=result["confidence"],
            source=SignalSource.CLAUDE,
            reasoning=result["reasoning"],
        )

    @retry(stop=stop_after_attempt(3), wait=wait_exponential(multiplier=1, min=2, max=10))
    async def _call_api(self, user_prompt: str) -> dict:
        message = self._client.messages.create(
            model=self._model,
            max_tokens=512,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": user_prompt}],
        )
        raw = message.content[0].text.strip()

        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]

        data = json.loads(raw)
        direction = Direction(data["direction"].upper())
        confidence = float(data["confidence"])
        reasoning = str(data.get("reasoning", ""))

        if not 0.0 <= confidence <= 1.0:
            raise ValueError(f"Invalid confidence: {confidence}")

        return {"direction": direction, "confidence": confidence, "reasoning": reasoning}
