"""
ClaudePromptBuilder — constructs the structured prompt sent to Claude.
Claude receives OHLCV data + all TA indicator values + ML prediction/probabilities.
Claude's role: reasoning layer + veto, NOT a price predictor.
"""
import json

from domain.entities import CandleSeries, Signal, SignalSource


class ClaudePromptBuilder:
    SYSTEM_PROMPT = """You are a professional Forex trading analyst and risk manager.
Your role is to evaluate trading signals generated by technical analysis and machine learning models,
and provide a final trading recommendation with clear reasoning.

You must respond in valid JSON with exactly this structure:
{
  "direction": "BUY" | "SELL" | "HOLD",
  "confidence": <float 0.0-1.0>,
  "reasoning": "<concise explanation, max 200 words>"
}

Rules:
- Do NOT act as a price predictor. Evaluate the evidence provided.
- A HOLD is valid and encouraged when signals conflict or context is ambiguous.
- Confidence above 0.70 in the OPPOSITE direction to the TA+ML consensus will VETO their recommendation.
- Be conservative: capital preservation over profit chasing.
"""

    def build(
        self,
        candles: CandleSeries,
        ta_signal: Signal,
        ml_signal: Signal,
    ) -> str:
        last = candles.candles[-1] if candles.candles else None
        last_candles_str = ""
        if candles.candles:
            recent = candles.candles[-5:]
            last_candles_str = "\n".join(
                f"  [{c.time.isoformat()}] O={c.open:.5f} H={c.high:.5f} L={c.low:.5f} C={c.close:.5f} V={c.volume:.0f}"
                for c in recent
            )

        ta_ctx = json.dumps(ta_signal.context, indent=2)
        ml_ctx = json.dumps(ml_signal.context, indent=2)

        return f"""# Forex Trading Signal Evaluation

## Instrument: {candles.instrument_symbol} | Timeframe: {candles.timeframe.value}

## Recent Candles (last 5):
{last_candles_str}

## Technical Analysis Signal
Direction: {ta_signal.direction.value}
Confidence: {ta_signal.confidence:.2f}
Indicators:
{ta_ctx}

## Machine Learning Signal (XGBoost 3-class classifier)
Direction: {ml_signal.direction.value}
Confidence: {ml_signal.confidence:.2f}
Probabilities:
{ml_ctx}

## Your Task
Review the TA and ML signals above. Consider:
1. Do the signals agree or conflict?
2. Are the TA indicators consistent with the ML probabilities?
3. Is the current market context suitable for a trade?

Respond with your JSON assessment."""
